In [1]:
import tensorflow as tf

In [3]:
# Initializing Tensors
x_int = tf.constant(4) # Int
print(x_int)

x_float = tf.constant(4.0) # Float
print(x_float)

x_shape = tf.constant(4, shape=(1,1)) # Int
print(x_shape)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4]], shape=(1, 1), dtype=int32)


Rank/Degree

In [4]:
x_string = tf.constant('Hello World', tf.string)
print(x_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [6]:
x_matrix = tf.constant([[1, 2], [3, 4]])
print(x_matrix)
print(x_matrix.shape)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
(2, 2)


Changing shapes

In [10]:
tensor1 = tf.ones([1, 2, 3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [15]:
tensor2 = tf.reshape(tensor1, [2, 3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [17]:
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
